project_id = "frfvrgarcwmpviimsenu"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
port = 54325

[auth]
enable_signup = true
email_confirm = false

[auth.email]
# Use our custom verification email function
enable_signup = true
double_confirm_changes = true
secure_email_change_enabled = true

[auth.external.google]
enabled = false

[auth.external.facebook]
enabled = false

[auth.external.twitter]
enabled = false

[auth.external.github]
enabled = false

[auth.external.apple]
enabled = false

[auth.external.azure]
enabled = false

[auth.external.bitbucket]
enabled = false

[auth.external.discord]
enabled = false

[auth.external.figma]
enabled = false

[auth.external.gitlab]
enabled = false

[auth.external.instagram]
enabled = false

[auth.external.kakao]
enabled = false

[auth.external.keycloak]
enabled = false

[auth.external.linkedin]
enabled = false

[auth.external.notion]
enabled = false

[auth.external.slack]
enabled = false

[auth.external.spotify]
enabled = false

[auth.external.twitch]
enabled = false

[auth.external.workos]
enabled = false

[auth.external.zoom]
enabled = false

[auth.hook.custom_access_token]
enabled = false

[auth.hook.send_sms]
enabled = false

[auth.hook.send_email]
enabled = false

[functions]
[functions.analyze-outfit]
verify_jwt = false

[functions.send-invites]
verify_jwt = false

[functions.send-rating-email]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.generate-recommendations]
verify_jwt = false

[functions.send-verification-email]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.generate-style-palette]
verify_jwt = false

[functions.analyze-style-profile]
verify_jwt = true