// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://frfvrgarcwmpviimsenu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZyZnZyZ2FyY3dtcHZpaW1zZW51Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NDY5NzUsImV4cCI6MjA2MzMyMjk3NX0.wKAEtuHhZVyVfCwuh9hJSDB3CeSgssZ7QTiPf9_xZSE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);